### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by wirwolf** [snwh/ubuntu-post-install#10]
./functions/check: строка 2: $'\r': команда не найдена
./functions/check: строка 4: $'\r': команда не найдена
./functions/check: строка 6: $'\r': команда не найдена
./functions/check: строка 8: ошибка синтаксиса около неожиданной лексемы `$'{\r''
'/functions/check: строка 8:`function check {
/functions/cleanup: Нет такого файла или каталога
/functions/codecs: Нет такого файла или каталога
/functions/configure: Нет такого файла или каталога
/functions/development: Нет такого файла или каталога
/functions/favourites: Нет такого файла или каталога
/functions/thirdparty: Нет такого файла или каталога
/functions/update: Нет такого файла или каталога
/functions/utilities: Нет такого файла или каталога
./ubuntu-post-install-script.sh: строка 102: check: команда не найдена

**Comment by snwh** [comment]
Please translate "Нет такого файла или каталога" for me.

**Comment by anowlcalledjosh** [comment]
Looks like "no such file or directory". Translated version (h/t Google):

```
./functions/check: line 2: $'\r': command not found
./functions/check: line 4: $'\r': command not found
./functions/check: line 6: $'\r': command not found
./functions/check: line 8: syntax error near unexpected token $'{\r'' '/functions/check: line 8:function check {
/functions/cleanup: No such file or directory
/functions/codecs: No such file or directory
/functions/configure: No such file or directory
/functions/development: No such file or directory
/functions/favourites: No such file or directory
/functions/thirdparty: No such file or directory
/functions/update: No such file or directory
/functions/utilities: No such file or directory
./ubuntu-post-install-script.sh: line 102: check: command not found
```

**Comment by snwh** [comment]
I can't confirm that this exists.

**Comment by qertis** [comment]
@wirwolf  у тебя неверный перевод строки 
http://www.cyberforum.ru/shell/thread1678951.html

**Comment by snwh** [comment]
Closing due to age and the function no longer being the same
