### ISSUE TITLE
Request functions: translation into other languages

### ISSUE THREAD

**Issue by gargullia** [snwh/ubuntu-post-install#11]
Is it possible to realize the translation to other languages using .po files example
Or by other methods

**Comment by snwh** [comment]
These scripts are only meant for personal use, you can translate it for yourself into whichever language you prefer.

**Comment by gargullia** [comment]
@snwh I ask only make a template such as a .po file. To me and other users to be able to translate.
Respectfully. Thank you

**Comment by snwh** [comment]
There's not that much demand for translations, nor is this distributed software. It's basically my personal script-set that people can copy for themselves.
