### ISSUE TITLE
Removing the packages listed in the file data/purge.list cause a dependency error

### ISSUE THREAD

**Issue by joaosalless** [snwh/ubuntu-post-install#5]
Removing the packages listed in the file data/purge.list cause a dependency error in unity-tweak-tool package.

```
overlay-scrollbar
overlay-scrollbar-gtk2
overlay-scrollbar-gtk3
webbrowser-app
```

 Tested on Ubuntu 15.04 with Unity.

Thank you for providing this wonderful script!

**Comment by snwh** [comment]
Just remove them from your version of the script. The .list files are simply my preferences.
