### ISSUE TITLE
Missing #6

### ISSUE THREAD

**Issue by koesherbacon** [snwh/ubuntu-post-install#7]
Hi there,

I just used your script and I'm very happy with it, however I did notice that it's missing the #6 entry.  

Here's a screenshot for you to take a look at:
http://i.imgsafe.org/7b5d211.png

Again, I'm very pleased with the script and it works fine, I just wanted to bring this to your attention :)

**Comment by snwh** [comment]
This isn't relevant with the new whiptail UI.
