### ISSUE TITLE
-yno: unknown option

### ISSUE THREAD

**Issue by dkozel** [snwh/ubuntu-post-install#9]
```
Ubuntu 15.04
whiptail (newt): 0.52.15
```
The main menu can't be quit because the whiptail call in the quit function fails, returning a value which evaluates to false.
https://github.com/snwh/ubuntu-post-install/blob/master/ubuntu-post-install-script.sh#L94

I'm adapting the script to for my needs and can submit a pull request reverting the usage of ```-yno``` if you would be interested.

**Comment by snwh** [comment]
Oops that's a search and replace gone wrong. There's more than one instance of that error. I've fixed it in the latest commit.
